name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
    # 1. Code එක ගන්නවා
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Python Setup කරනවා
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Dependencies Install කරනවා
    - name: Install Dependencies
      run: |
        pip install bandit
        pip install -r requirements.txt

    # 4. Bandit Scan (SAST) - Code එකේ වැරදි බලනවා
    - name: Run Bandit Security Scan
      run: |
        bandit -r .

    # 5. Docker Image එක හදනවා (Build)
    # Trivy වලට Scan කරන්න නම් Image එකක් තියෙන්න ඕනනේ.
    - name: Build Docker Image
      run: docker build -t my-secure-app:${{ github.sha }} .

# 6. Trivy Image Scan (Strict Mode)
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-secure-app:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: false  # <--- විසඳුම් නැති ඒවත් අල්ලන්න
        vuln-type: 'os,library'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL' # <--- හැම එකම අල්ලන්න
